name: Ban abusing IPs
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: yarn install --frozen-lockfile
      - run: npm run ipban
        env:
          CLOUDFLARE_ACCOUNT: ${{ secrets.CLOUDFLARE_ACCOUNT }}
          BLACKLIST_ID: ${{ secrets.BLACKLIST_ID }}
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
          LOGS_API_USER: ${{ secrets.LOGS_API_USER }}
          LOGS_API_PASSWORD: ${{ secrets.LOGS_API_PASSWORD }}
          LOGS_API_TEAM: ${{ secrets.LOGS_API_TEAM }}
          LOGS_API_SOURCE: ${{ secrets.LOGS_API_SOURCE }}
          TZ: UTC
